# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='frytki',
            field=models.CharField(blank=True, choices=[('Dev', 'Dev'), ('Shop', 'Shop'), ('Cars', 'Cars')], max_length=64, verbose_name='frytki'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='instaacc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intagram Account'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
